import { Attributes } from "./kigardModels";

export const profileBeginnerWarrior: Attributes = {
    con: 7,
    str: 7,
    dex: 5,
    int: 5,
    lck: 0,
    acc: 35,
    dodge: 20,
    mm: 15,
    mr: 25,
    rpm: 1,
    rpv: 0,
    armor: 4,
    minDamage: 3, // short sword
    maxDamage: 5,
    minRange: 0,
    maxRange: 0,
    allowedWeight: 0,
    pv: 70,
    mp: 25,
    nbSpellAttach: 1,
    nbProjectiles: 0,
    isBow: 0,
    isRifle: 0,
    burning: 2, //fireball
    regeneration: 0,
    poison: 0,
    bleeding: 0,
    knockedOut: 0,
    breach: 0,
    terror: 0,
    necrosis: 0
};

export const profileIntermediateWarrior: Attributes = {
    con: 10,
    str: 10,
    dex: 6,
    int: 5,
    lck: 0,
    acc: 40,
    dodge: 30,
    mm: 15,
    mr: 40,
    rpm: 1,
    rpv: 0,
    armor: 8,
    minDamage: 5, // fléau
    maxDamage: 10,
    minRange: 0,
    maxRange: 0,
    allowedWeight: 0,
    pv: 100,
    mp: 25,
    nbSpellAttach: 1,
    nbProjectiles: 0,
    isBow: 0,
    isRifle: 0,
    burning: 2, //fireball
    regeneration: 0,
    poison: 0,
    bleeding: 0,
    knockedOut: 0,
    breach: 0,
    terror: 0,
    necrosis: 0
};

export const profileAdvancedWarrior: Attributes = {
    con: 11,
    str: 13,
    dex: 7,
    int: 5,
    lck: 0,
    acc: 60,
    dodge: 40,
    mm: 15,
    mr: 60,
    rpm: 1,
    rpv: 0,
    armor: 11,
    minDamage: 6, // lance
    maxDamage: 10,
    minRange: 0,
    maxRange: 0,
    allowedWeight: 0,
    pv: 110,
    mp: 25,
    nbSpellAttach: 1,
    nbProjectiles: 0,
    isBow: 0,
    isRifle: 0,
    burning: 2, //fireball
    regeneration: 0,
    poison: 0,
    bleeding: 0,
    knockedOut: 0,
    breach: 1,
    terror: 0,
    necrosis: 0
};

export const profileBeginnerAssassin: Attributes = {
    con: 6,
    str: 5,
    dex: 8,
    int: 5,
    lck: 0,
    acc: 50,
    dodge: 35,
    mm: 15,
    mr: 15,
    rpm: 1,
    rpv: 0,
    armor: 3,
    minDamage: 0, // poignard
    maxDamage: 4,
    minRange: 0,
    maxRange: 0,
    allowedWeight: 0,
    pv: 70,
    mp: 25,
    nbSpellAttach: 1,
    nbProjectiles: 0,
    isBow: 0,
    isRifle: 0,
    burning: 2, //fireball
    regeneration: 0,
    poison: 0,
    bleeding: 0,
    knockedOut: 0,
    breach: 1,
    terror: 0,
    necrosis: 0
};

export const profileIntermediateAssassin: Attributes = {
    con: 8,
    str: 6,
    dex: 10,
    int: 5,
    lck: 0,
    acc: 65,
    dodge: 50,
    mm: 15,
    mr: 15,
    rpm: 1,
    rpv: 0,
    armor: 5,
    minDamage: 0, // poignard
    maxDamage: 4,
    minRange: 0,
    maxRange: 0,
    allowedWeight: 0,
    pv: 80,
    mp: 25,
    nbSpellAttach: 1,
    nbProjectiles: 0,
    isBow: 0,
    isRifle: 0,
    burning: 2, //fireball
    regeneration: 0,
    poison: 0,
    bleeding: 0,
    knockedOut: 0,
    breach: 1,
    terror: 0,
    necrosis: 0
};

export const profileAdvancedAssassin: Attributes = {
    con: 9,
    str: 7,
    dex: 15,
    int: 5,
    lck: 0,
    acc: 90,
    dodge: 70,
    mm: 15,
    mr: 15,
    rpm: 1,
    rpv: 0,
    armor: 8,
    minDamage: 0, // poignard
    maxDamage: 4,
    minRange: 0,
    maxRange: 0,
    allowedWeight: 0,
    pv: 90,
    mp: 25,
    nbSpellAttach: 1,
    nbProjectiles: 0,
    isBow: 0,
    isRifle: 0,
    burning: 2, //fireball
    regeneration: 0,
    poison: 0,
    bleeding: 0,
    knockedOut: 0,
    breach: 1,
    terror: 0,
    necrosis: 0
};

export const profileBeginnerMage: Attributes = {
    con: 6,
    str: 5,
    dex: 5,
    int: 8,
    lck: 0,
    acc: 15,
    dodge: 20,
    mm: 25,
    mr: 15,
    rpm: 2,
    rpv: 0,
    armor: 2,
    minDamage: 1, // scepter
    maxDamage: 3,
    minRange: 0,
    maxRange: 0,
    allowedWeight: 0,
    pv: 60,
    mp: 25,
    nbSpellAttach: 1,
    nbProjectiles: 0,
    isBow: 0,
    isRifle: 0,
    burning: 2, //fireball
    regeneration: 0,
    poison: 0,
    bleeding: 0,
    knockedOut: 0,
    breach: 0,
    terror: 0,
    necrosis: 0
};

export const profileIntermediateMage: Attributes = {
    con: 8,
    str: 5,
    dex: 5,
    int: 12,
    lck: 0,
    acc: 15,
    dodge: 20,
    mm: 35,
    mr: 20,
    rpm: 2,
    rpv: 0,
    armor: 3,
    minDamage: 1, // scepter
    maxDamage: 3,
    minRange: 0,
    maxRange: 0,
    allowedWeight: 0,
    pv: 80,
    mp: 25,
    nbSpellAttach: 1,
    nbProjectiles: 0,
    isBow: 0,
    isRifle: 0,
    burning: 2, //fireball
    regeneration: 0,
    poison: 0,
    bleeding: 0,
    knockedOut: 0,
    breach: 0,
    terror: 0,
    necrosis: 0
};

export const profileAdvancedMage: Attributes = {
    con: 9,
    str: 5,
    dex: 5,
    int: 17,
    lck: 0,
    acc: 15,
    dodge: 30,
    mm: 55,
    mr: 25,
    rpm: 4,
    rpv: 0,
    armor: 4,
    minDamage: 1, // scepter
    maxDamage: 3,
    minRange: 0,
    maxRange: 0,
    allowedWeight: 0,
    pv: 90,
    mp: 25,
    nbSpellAttach: 1,
    nbProjectiles: 0,
    isBow: 0,
    isRifle: 0,
    burning: 2, //fireball
    regeneration: 0,
    poison: 0,
    bleeding: 0,
    knockedOut: 0,
    breach: 0,
    terror: 0,
    necrosis: 0
};